version: "3"

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    networks:
      - symfony

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: username_db
      POSTGRES_PASSWORD: password_symfony
    ports:
      - "5433:5432"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
