<?php
//Class generated by Adenagbe Emmanuel on 15/07/2024
namespace App\DataFixtures;

use App\Entity\Product;
use Doctrine\Persistence\ObjectManager;

class ProductFixture
{

    public function load(ObjectManager $manager): void
    {
        $product = new Product();
        $product->setProductName('Apple iPhone 13 Pro');
        $product->setProductDescription('The Apple iPhone 13 Pro is a smartphone that was designed, manufactured, and sold by Apple Inc. It is the fourteenth generation of the iPhone, succeeding the iPhone 12 and preceding the iPhone 14. It was announced on September 14, 2021, alongside the iPhone 13, iPhone 13 Mini, and iPhone 13 Pro Max at the Apple Event at Apple Park in Cupertino, California.');
        $product->setProductPrice(999.99);
        $product->setProductImage('https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-family-hero?wid=940&hei=1112&fmt=jpeg&qlt=80&.v=1631659848000');
        $manager->persist($product);
        $manager->flush();
    }
}
